name: Re-subscribe Mailing Lists

on:
  schedule:
    # Runs every 30 minutes
    - cron: "*/30 * * * *"

env:
  LISTMONK_TOKEN: ${{ secrets.LISTMONK_TOKEN }}

jobs:
  resubscribe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
      - name: Run the script
        run: |
          cd resubscribe-mailing-lists
          deno task start
